IF OBJECT_ID ('ST_CLASSIFICACOES_CLIENTES' ) IS NULL 

BEGIN

CREATE TABLE ST_CLASSIFICACOES_CLIENTES 
			 (	
				NOME_CLASSIFICAO VARCHAR ( 60 )
			 ,  CLASSIFICACAO_CLIENTE NUMERIC ( 15 )
			 )

END

TRUNCATE TABLE ST_CLASSIFICACOES_CLIENTES

INSERT INTO ST_CLASSIFICACOES_CLIENTES
			 (	
				NOME_CLASSIFICAO	
			 ,  CLASSIFICACAO_CLIENTE		
			 )

	    SELECT
				B.DESCRICAO	
			 ,  B.CLASSIFICACAO_CLIENTE	
		  FROM
				PBS_PROCFIT_DADOS.DBO.CLASSIFICACOES_CLIENTES B