IF OBJECT_ID ( 'ENTIDADE' ) IS NOT NULL DROP TABLE ST_CLIENTES

CREATE TABLE ST_CLIENTES
			 (	
				ENTIDADE NUMERIC ( 12 )
			 ,  NOME VARCHAR ( 50 )
			 ,  NOME_FANTASIA VARCHAR ( 50 )
			 ,  CLASSIFICACAO_CLIENTE NUMERIC ( 15 )
			 )


TRUNCATE TABLE ST_CLIENTES

INSERT INTO ST_CLIENTES
			 (	
				ENTIDADE				
			 ,  NOME					
			 ,  NOME_FANTASIA			
			 ,  CLASSIFICACAO_CLIENTE	
			 )

	    SELECT
				A.ENTIDADE				
			 ,  A.NOME					
			 ,  A.NOME_FANTASIA			
			 ,  A.CLASSIFICACAO_CLIENTE	
		  FROM
				PBS_PROCFIT_DADOS.DBO.ENTIDADES A
	   