CREATE TABLE DW_PRODUTOS

	(
		COD_PRODUTO			 NUMERIC ( 010 ) PRIMARY KEY
	 ,  DESCRICAO			 VARCHAR ( 100 )
	 ,  DESCRICAO_REDUZIDA	 VARCHAR ( 060 )
	 ,  FAMILIA				 VARCHAR ( 060 )
	 ,  SECAO				 VARCHAR ( 060 )
	 ,  GRUPO				 VARCHAR ( 060 )
	 ,  SUB_GRUPO			 VARCHAR ( 060 )
	 ,  MARCA				 VARCHAR ( 060 )
	)