SELECT
		A.PRODUTO
	 ,  A.DESCRICAO
	 ,  A.DESCRICAO_REDUZIDA
	 ,  B.DESCRICAO						AS FAMILIA
	 ,  C.DESCRICAO						AS SECAO
	 ,  D.DESCRICAO						AS GRUPO
	 ,  E.DESCRICAO						AS SUB_GRUPO
	 ,  F.DESCRICAO						AS MARCA
  FROM
		PRODUTOS					A
		LEFT JOIN FAMILIAS_PRODUTOS B	ON A.FAMILIA_PRODUTO  =	B.FAMILIA_PRODUTO
		JOIN SECOES_PRODUTOS		C	ON A.SECAO_PRODUTO    =	C.SECAO_PRODUTO
		JOIN GRUPOS_PRODUTOS		D	ON A.GRUPO_PRODUTO    =	D.GRUPO_PRODUTO
		JOIN SUBGRUPOS_PRODUTOS     E   ON A.SUBGRUPO_PRODUTO = E.SUBGRUPO_PRODUTO
		LEFT JOIN MARCAS			F   ON A.MARCA            = F.MARCA
