CREATE PROCEDURE USP_ST_PRODUTOS

AS

BEGIN

----------------------------------
--TESTA A EXISTENCIA DAS TABELAS--
----------------------------------


IF OBJECT_ID ( 'PBS_PROCFIT_ST..ST_PRODUTOS' ) IS NULL

BEGIN

CREATE TABLE ST_PRODUTOS
	(
		COD_PRODUTO			 NUMERIC ( 010 )
	 ,  DESCRICAO			 VARCHAR ( 100 )
	 ,  DESCRICAO_REDUZIDA	 VARCHAR ( 060 )
	 ,  FAMILIA				 VARCHAR ( 060 )
	 ,  SECAO				 VARCHAR ( 060 )
	 ,  GRUPO				 VARCHAR ( 060 )
	 ,  SUB_GRUPO			 VARCHAR ( 060 )
	 ,  MARCA				 VARCHAR ( 060 )
	)

END


----------------------------------
--       POPULA AS TABELAS      --
----------------------------------

TRUNCATE TABLE ST_PRODUTOS

INSERT INTO ST_PRODUTOS
	(
		COD_PRODUTO			
	 ,  DESCRICAO			
	 ,  DESCRICAO_REDUZIDA	
	 ,  FAMILIA				
	 ,  SECAO				
	 ,  GRUPO				
	 ,  SUB_GRUPO			
	 ,  MARCA				
	)

SELECT
		A.PRODUTO
	 ,  A.DESCRICAO
	 ,  A.DESCRICAO_REDUZIDA
	 ,  B.DESCRICAO						AS FAMILIA
	 ,  C.DESCRICAO						AS SECAO
	 ,  D.DESCRICAO						AS GRUPO
	 ,  E.DESCRICAO						AS SUB_GRUPO
	 ,  F.DESCRICAO						AS MARCA
  FROM
		PBS_PROCFIT_DADOS..PRODUTOS						A
		LEFT JOIN PBS_PROCFIT_DADOS..FAMILIAS_PRODUTOS	B	ON A.FAMILIA_PRODUTO  =	B.FAMILIA_PRODUTO
		JOIN PBS_PROCFIT_DADOS..SECOES_PRODUTOS			C	ON A.SECAO_PRODUTO    =	C.SECAO_PRODUTO
		JOIN PBS_PROCFIT_DADOS..GRUPOS_PRODUTOS			D	ON A.GRUPO_PRODUTO    =	D.GRUPO_PRODUTO
		JOIN PBS_PROCFIT_DADOS..SUBGRUPOS_PRODUTOS		E   ON A.SUBGRUPO_PRODUTO = E.SUBGRUPO_PRODUTO
		LEFT JOIN PBS_PROCFIT_DADOS..MARCAS				F   ON A.MARCA            = F.MARCA

END