MERGE DW_VENDEDORES						D
USING PBS_PROCFIT_ST.DBO.VW_VENDEDORES	O	ON	D.COD_VENDEDOR = O.COD_VENDEDOR

WHEN MATCHED THEN UPDATE
				SET
					COD_VENDEDOR	=	O.COD_VENDEDOR
				,	VENDEDOR		=	O.VENDEDOR
				

WHEN NOT MATCHED BY TARGET THEN 

				INSERT
				(
					COD_VENDEDOR
				,	VENDEDOR
				)

				VALUES
				(
					O.COD_VENDEDOR
				,	O.VENDEDOR
				)

WHEN NOT MATCHED BY SOURCE THEN DELETE

;