
IF OBJECT_ID ( 'PBS_PROCFIT_DW.DBO.DW_EMPRESAS' ) IS NULL

BEGIN

CREATE TABLE DW_EMPRESAS
		(
			COD_EMPRESA		NUMERIC ( 038 ) PRIMARY KEY
		,	NOME			VARCHAR	( 200 )
		,	NOME_FANTASIA	VARCHAR	( 200 )
		)

END