CREATE PROCEDURE USP_ST_LIMPA_BANCO

AS

TRUNCATE TABLE ST_CLASSIFICACOES_CLIENTES

TRUNCATE TABLE ST_CLIENTES

TRUNCATE TABLE ST_EMPRESAS

TRUNCATE TABLE ST_ENDERECOS

TRUNCATE TABLE ST_ESTADO

TRUNCATE TABLE ST_PRODUTOS

TRUNCATE TABLE ST_VENDAS

TRUNCATE TABLE ST_VENDEDORES