
IF OBJECT_ID ( 'PBS_PROCFIT_DW.DBO.DW_CLIENTES' ) IS NULL

BEGIN

CREATE TABLE DW_CLIENTES
			 (
				ENTIDADE		NUMERIC ( 038 ) PRIMARY KEY
			 ,  NOME			VARCHAR ( 200 )
			 ,  NOME_FANTASIA	VARCHAR ( 200 )
			 ,  CLASSIFICAO		VARCHAR ( 200 )
			 ,  CIDADE			VARCHAR ( 200 )
			 ,  ESTADO			VARCHAR ( 200 )
			 ,  UF				CHAR	( 002 )
			 )

END