TRUNCATE TABLE DW_VENDAS

INSERT INTO DW_VENDAS
		(
		    N_DOC			
		,   COD_EMPRESA		
		,   COD_CLIENTE		
		,   COD_VENDEDOR	
		,	MOVIMENTO		
		,	COD_PRODUTO		
		,	QUANTIDADE		
		,	VENDA_BRUTA		
		,	DESCONTO_TOTAL	
		,	VENDA_LIQUIDA	
		)

	    (
	SELECT
		    N_DOC			
		,   COD_EMPRESA		
		,   COD_CLIENTE		
		,   COD_VENDEDOR	
		,	MOVIMENTO		
		,	COD_PRODUTO		
		,	QUANTIDADE		
		,	VENDA_BRUTA		
		,	DESCONTO_TOTAL	
		,	VENDA_LIQUIDA	
	  FROM
			PBS_PROCFIT_ST.DBO.VW_VENDAS
		)