IF OBJECT_ID ( 'PBS_PROCFIT_DW.DBO.DW_VENDAS' ) IS NULL

BEGIN

CREATE TABLE DW_VENDAS
(
    N_DOC			NUMERIC ( 09 )
,   COD_EMPRESA		NUMERIC ( 38 )	REFERENCES DW_EMPRESAS   ( COD_EMPRESA  )
,   COD_CLIENTE		NUMERIC ( 38 )	REFERENCES DW_CLIENTES   ( COD_CLIENTE  )	
,   COD_VENDEDOR	NUMERIC ( 32 )	REFERENCES DW_VENDEDORES ( COD_VENDEDOR )
,	MOVIMENTO		DATE
,	COD_PRODUTO		NUMERIC ( 10 )	REFERENCES DW_PRODUTOS   ( COD_PRODUTO  )
,	QUANTIDADE		INT
,	VENDA_BRUTA		MONEY
,	DESCONTO_TOTAL	MONEY
,	VENDA_LIQUIDA	MONEY
)

END