CREATE PROCEDURE USP_DW_F_VENDAS ( @INCREMENTAL BIT )

-- CARGA INCREMENTAL	@INCREMENTAL	=	1
-- CARGA FULL			@INCREMENTAL	=	0

AS

----------------------------------
--TESTA A EXISTENCIA DAS TABELAS--
----------------------------------

IF OBJECT_ID ( 'PBS_PROCFIT_DW.DBO.DW_VENDAS' ) IS NULL

BEGIN

CREATE TABLE DW_VENDAS
(
    N_DOC			NUMERIC ( 09 )
,   COD_EMPRESA		NUMERIC ( 38 )	REFERENCES DW_EMPRESAS   ( COD_EMPRESA  )
,   COD_CLIENTE		NUMERIC ( 38 )	REFERENCES DW_CLIENTES   ( COD_CLIENTE  )	
,   COD_VENDEDOR	NUMERIC ( 32 )	REFERENCES DW_VENDEDORES ( COD_VENDEDOR )
,	MOVIMENTO		DATE
,	COD_PRODUTO		NUMERIC ( 10 )	REFERENCES DW_PRODUTOS   ( COD_PRODUTO  )
,	QUANTIDADE		INT
,	VENDA_BRUTA		MONEY
,	DESCONTO_TOTAL	MONEY
,	VENDA_LIQUIDA	MONEY
)

END

----------------------------------
--       LIMPA AS TABELAS       --
----------------------------------

IF @INCREMENTAL = 0
BEGIN

TRUNCATE TABLE DW_VENDAS

END

----------------------------------
--       POPULA AS TABELAS      --
----------------------------------

INSERT INTO DW_VENDAS
		(
		    N_DOC			
		,   COD_EMPRESA		
		,   COD_CLIENTE		
		,   COD_VENDEDOR	
		,	MOVIMENTO		
		,	COD_PRODUTO		
		,	QUANTIDADE		
		,	VENDA_BRUTA		
		,	DESCONTO_TOTAL	
		,	VENDA_LIQUIDA	
		)

	    (
	SELECT
		    N_DOC			
		,   COD_EMPRESA		
		,   COD_CLIENTE		
		,   COD_VENDEDOR	
		,	MOVIMENTO		
		,	COD_PRODUTO		
		,	QUANTIDADE		
		,	VENDA_BRUTA		
		,	DESCONTO_TOTAL	
		,	VENDA_LIQUIDA	
	  FROM
			PBS_PROCFIT_ST.DBO.VW_VENDAS
	    )