CREATE VIEW VW_VENDEDORES

AS

SELECT	
		0								AS COD_VENDEDOR
	 ,  'Não Informado'					AS VENDEDOR

UNION ALL

SELECT 
		COD_VENDEDOR
	 ,  DBO.FN_PASCAL_CASE ( VENDEDOR ) AS VENDEDOR
  FROM 
		ST_VENDEDORES