CREATE VIEW VW_VENDAS

AS

SELECT 
		COALESCE ( N_DOC        , 0 )	AS N_DOC
	 ,  COALESCE ( COD_EMPRESA  , 0 )	AS COD_EMPRESA
	 ,  COALESCE ( COD_CLIENTE  , 0 )	AS COD_CLIENTE
	 ,	COALESCE ( COD_VENDEDOR , 0 )	AS COD_VENDEDOR
	 ,	MOVIMENTO
	 ,	COALESCE ( COD_PRODUTO  , 0 )	AS COD_PRODUTO
	 ,	QUANTIDADE
	 ,	VENDA_BRUTA
	 ,	DESCONTO_TOTAL
	 ,	VENDA_LIQUIDA
  FROM 
		ST_VENDAS

